module.exports = {
  displayName: '253Pay Backend',
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/*.spec.ts',
    '!**/node_modules/**',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  moduleNameMapper: {
    '^@common/(.*)$': '<rootDir>/common/$1',
    '^@config/(.*)$': '<rootDir>/config/$1',
    '^@database/(.*)$': '<rootDir>/database/$1',
    '^@auth/(.*)$': '<rootDir>/auth/$1',
    '^@users/(.*)$': '<rootDir>/users/$1',
    '^@wallets/(.*)$': '<rootDir>/wallets/$1',
    '^@ledger/(.*)$': '<rootDir>/ledger/$1',
    '^@transactions/(.*)$': '<rootDir>/transactions/$1',
    '^@transfers/(.*)$': '<rootDir>/transfers/$1',
    '^@deposits/(.*)$': '<rootDir>/deposits/$1',
    '^@withdrawals/(.*)$': '<rootDir>/withdrawals/$1',
    '^@agents/(.*)$': '<rootDir>/agents/$1',
    '^@merchants/(.*)$': '<rootDir>/merchants/$1',
    '^@payments/(.*)$': '<rootDir>/payments/$1',
    '^@providers/(.*)$': '<rootDir>/providers/$1',
    '^@kyc/(.*)$': '<rootDir>/kyc/$1',
    '^@notifications/(.*)$': '<rootDir>/notifications/$1',
    '^@fees/(.*)$': '<rootDir>/fees/$1',
    '^@limits/(.*)$': '<rootDir>/limits/$1',
    '^@audit/(.*)$': '<rootDir>/audit/$1',
    '^@admin/(.*)$': '<rootDir>/admin/$1',
    '^@webhooks/(.*)$': '<rootDir>/webhooks/$1',
  },
};
